# Render Blueprint Specification
# This file defines the infrastructure for your multi-tenant memory application

services:
  # Backend API Service
  - type: web
    name: jonathans-memory-api
    runtime: python
    region: oregon
    plan: starter # $7/month
    rootDir: openmemory/api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/health"
    envVars:
      # Database Configuration - Will be automatically set from the database
      - key: DATABASE_URL
        fromDatabase:
          name: jonathans-memory-db
          property: connectionString
      
      # Supabase Configuration (Required - Set in dashboard)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      
      # OpenAI Configuration (Required - Set in dashboard)
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: "openai"
      - key: OPENAI_MODEL
        value: "gpt-4o-mini"
      - key: EMBEDDER_PROVIDER
        value: "openai"
      - key: EMBEDDER_MODEL
        value: "text-embedding-ada-002"
      
      # Qdrant Configuration (Required - Set in dashboard)
      - key: QDRANT_HOST
        sync: false
      - key: QDRANT_PORT
        value: "6333"
      - key: QDRANT_API_KEY
        sync: false
      - key: MAIN_QDRANT_COLLECTION_NAME
        value: "jonathans_memory_main"
      
      # Runtime Configuration
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"

  # Frontend UI Service
  - type: web
    name: jonathans-memory-ui
    runtime: node
    region: oregon
    plan: starter # $7/month
    rootDir: openmemory/ui
    buildCommand: "pnpm install && pnpm build"
    startCommand: "pnpm start"
    envVars:
      # Supabase Configuration (Public keys - Set in dashboard)
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      
      # Backend API URL - Automatically set from backend service
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: jonathans-memory-api
          property: host
      
      # Runtime
      - key: NODE_ENV
        value: "production"

# PostgreSQL Database for backend metadata
databases:
  - name: jonathans-memory-db
    databaseName: openmemory
    user: openmemory
    region: oregon
    plan: basic-256mb # Basic tier - 256MB RAM, 1GB storage
    ipAllowList: [] # Allow connections from Render services 