version: '3.8'

services:
  # Qdrant Vector Database - Still needed as Supabase doesn't provide vector storage
  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: openmemory_qdrant_service
    restart: always
    ports:
      - "6333:6333" # HTTP/REST API
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - memory_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:

networks:
  memory_network:
    driver: bridge
