name = "jean-memory-mcp"
main = "src/index.ts"
compatibility_date = "2024-06-01"

# Production environment
[env.production]
vars = { BACKEND_URL = "https://jean-memory-api-virginia.onrender.com" }

# Durable Objects binding
[[durable_objects.bindings]]
name = "MCP_SESSION"
class_name = "McpSession"

# Durable Objects migration
[[migrations]]
tag = "v1"
new_classes = ["McpSession"]

# Development environment (optional)
[env.development]
vars = { BACKEND_URL = "http://localhost:8000" }